apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: meao-monitoring
  name: meao-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meao-monitoring
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: meao-monitoring
    spec:
      containers:
        - env:
            - name: KAFKA_SERVER
              value: 10.255.32.132:31999
            - name: KUBECTL_COMMAND
              value: /usr/local/bin/kubectl
            - name: KUBECTL_CONFIG_PATH
              value: kube_config
            - name: METRICS_COLLECTOR_KAFKA_TOPIC
              value: k8s-cluster
            - name: OSM_HOSTNAME
              value: nbi.10.255.32.132.nip.io
            - name: MEAO_OSS_KAFKA_TOPIC
              value: meao-oss
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: UE_LATENCY_KAFKA_TOPIC
              value: ue-lat
            - name: SEND_CONTAINER_INFO_FREQ
              value: "5"
          image: localhost:5000/meao-monitoring
          imagePullPolicy: Always
          name: meao-monitoring
          ports:
            - containerPort: 8000
              protocol: TCP
      restartPolicy: Always
